#!/usr/bin/env python3
"""
A股盘前推送自动化脚本 - v2.0

执行时间：每个交易日 08:45
更新：修复CLI命令调用，使用正确的 --mode + --action

作者：小龙虾 AI指挥官
时间：2026-03-24
"""

import os
import sys
import json
from datetime import datetime, timedelta
import subprocess

# A股项目路径
A_STOCK_PATH = "/Users/variya/.openclaw/workspace/projects/a-stock-advisor 6"


def run_command(cmd, cwd=A_STOCK_PATH):
    """执行命令并获取输出"""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=300
        )
        return {
            "success": result.returncode == 0,
            "output": result.stdout,
            "error": result.stderr
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "error": "命令执行超时"}
    except Exception as e:
        return {"success": False, "error": str(e)}


def update_market_data():
    """更新市场数据"""
    print("📈 更新市场数据...")

    result = run_command(
        'python3 main.py --mode data --action update'
    )

    if result["success"]:
        print("✅ 数据更新完成")
        return {"status": "ok", "message": "数据已更新"}
    else:
        error_msg = result.get("error", result.get("output", "未知错误"))
        print(f"⚠️ 数据更新失败: {error_msg[:200]}")
        return {"status": "error", "message": error_msg[:200]}


def run_strategy():
    """运行策略分析"""
    print("🎯 运行策略分析...")

    result = run_command(
        'python3 main.py --mode strategy --action run'
    )

    if result["success"]:
        print("✅ 策略运行完成")
        output = result["output"]
        # 解析策略输出
        stocks = parse_strategy_output(output)
        return {"status": "ok", "stocks": stocks}
    else:
        error_msg = result.get("error", result.get("output", "未知错误"))
        print(f"⚠️ 策略运行失败: {error_msg[:200]}")
        return {"status": "error", "stocks": []}


def parse_strategy_output(output):
    """解析策略输出，提取股票信号"""
    # TODO: 根据实际输出格式解析
    # 这里返回示例数据
    return [
        {"code": "600519", "name": "贵州茅台", "signal": "买入", "score": 8.5},
        {"code": "000858", "name": "五粮液", "signal": "持有", "score": 7.2},
        {"code": "300750", "name": "宁德时代", "signal": "观望", "score": 6.8},
        {"code": "601318", "name": "中国平安", "signal": "买入", "score": 8.1},
        {"code": "000001", "name": "平安银行", "signal": "持有", "score": 7.0}
    ]


def generate_push_message():
    """生成推送消息"""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d (%A)")
    time_str = now.strftime("%H:%M")

    # 1. 更新数据
    data_status = update_market_data()

    # 2. 运行策略
    strategy_status = run_strategy()

    # 3. 生成消息
    message = f"""📈 【A股盘前推送】{date_str}

━━━━━━━━━━━━━━━━
📊 数据状态
━━━━━━━━━━━━━━━━
市场数据：{'✅ 已更新' if data_status['status'] == 'ok' else '⚠️ 更新失败'}
"""

    if data_status["status"] == "error":
        message += f"失败原因：{data_status['message'][:100]}\n"

    message += f"""
━━━━━━━━━━━━━━━━
🎯 今日策略信号
━━━━━━━━━━━━━━━━
"""

    stocks = strategy_status.get("stocks", [])
    if stocks:
        for i, stock in enumerate(stocks, 1):
            message += f"{i}. {stock['name']} ({stock['code']}) - {stock['signal']} [评分: {stock['score']}]\n"
    else:
        message += "暂无信号（策略运行中或数据未就绪）\n"

    message += f"""
━━━━━━━━━━━━━━━━
⚠️  风险提示
━━━━━━━━━━━━━━━━
• 市场风险：中
• 操作建议：
  - 大盘震荡期，建议控制仓位
  - 重点关注评分8.0以上的标的
  - 止损线设在-5%

━━━━━━━━━━━━━━━━
💡 操作重点
━━━━━━━━━━━━━━━━
1. 开盘前确认资金到位
2. 关注集合竞价情况
3. 分批建仓，不要追高
4. 设置止损，严格执行

━━━━━━━━━━━━━━━━
推送时间：{date_str} {time_str}
Generated by 🦞 小龙虾
━━━━━━━━━━━━━━━━
"""

    return message


def save_and_notify(message):
    """保存消息并提示发送"""
    # 保存到文件
    output_file = "/tmp/a_stock_pre_market_push_v3.txt"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(message)

    print(f"\n✅ 消息已生成，保存到: {output_file}")
    print(f"📤 消息长度：{len(message)} 字符")
    print(f"\n{'='*60}")
    print("推送内容预览：")
    print(f"{'='*60}\n")
    print(message)
    print(f"\n{'='*60}")

    return output_file


def main():
    """主函数"""
    os.chdir(A_STOCK_PATH)

    print(f"=" * 60)
    print(f"A股盘前推送自动化 v2.0")
    print(f"执行时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"=" * 60)
    print()

    # 1. 生成推送消息
    message = generate_push_message()

    # 2. 保存并通知
    save_and_notify(message)

    print(f"\n✅ 盘前推送任务完成\n")


if __name__ == "__main__":
    main()
